import { db , onValue, ref, set} from '../clientApp/clientApp';
import Head from "next/head";
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';

const Layout = ({ title, children }) => {
	const router = useRouter()
	const [Mode, setMode] = useState(false);

	const onChangeModeBtnClick = () => {
		set(ref(db, "agritech/mode"), {
			status: (Mode ? 0 : 1)
		  }).catch(alert);
		  setMode(!Mode);
		  router.push(!Mode ? "automatic" : "mannualy");
	};

	useEffect(() => {
		onValue(ref(db, "agritech/mode"), (snapshot) => {
		  if (snapshot.val().status == 1) {setMode(true)};
		});
	  }, [])
  	return <>
		<Head>
			<title>{title}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<header className="absolute top-0 left-0 w-full h-20 px-10 flex justify-between items-center bg-gray-800 text-gray-50">
			<div className="h-full flex items-center text-lg">
				<span className="uppercase text-3xl mr-1 tracking-widest text-green-200">sfis</span>
				<span> - Smart Farm Irrigation System</span>
			</div>
			<div className='flex items-center'>
				<span className='capitalize'>{Mode ? "automatic" : "mannualy"}</span>
				<button className='bg-green-600 ml-6 py-2 px-4 rounded hover:bg-green-700' onClick={onChangeModeBtnClick}>Change</button>
			</div>
		</header>
	
		<main className='w-full h-screen bg-gray-900'>
			{children}
		</main>

		<footer className="">
		</footer>
  </>;
};

export default Layout;
